<?php

/**
 * @file
 * Contains user_profile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_profile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_profile module.
    case 'help.page.user_profile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('multi-step form in Drupal 8 where users add the uinfo profile') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_profile_theme() {
  return [
    'user_profile' => [
      'render element' => 'children',
    ],
  ];
}

function user_profile_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ('user_info_one_form' == $form_id || 'user_info_two_form' == $form_id) {
    $form['#attached']['library'][] = 'user_profile/user_profile';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function user_profile_page_attachments_alter(array &$attachments) {
  //$attachments['#attached']['library'][] = 'user_profile/materialize';
}